// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.21.9
// source: protobuf/skeleton.proto

package skeleton

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// WalkingSkeletonClient is the client API for WalkingSkeleton service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type WalkingSkeletonClient interface {
	Walk(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (*WalkReply, error)
}

type walkingSkeletonClient struct {
	cc grpc.ClientConnInterface
}

func NewWalkingSkeletonClient(cc grpc.ClientConnInterface) WalkingSkeletonClient {
	return &walkingSkeletonClient{cc}
}

func (c *walkingSkeletonClient) Walk(ctx context.Context, in *WalkRequest, opts ...grpc.CallOption) (*WalkReply, error) {
	out := new(WalkReply)
	err := c.cc.Invoke(ctx, "/skeleton.WalkingSkeleton/Walk", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// WalkingSkeletonServer is the server API for WalkingSkeleton service.
// All implementations must embed UnimplementedWalkingSkeletonServer
// for forward compatibility
type WalkingSkeletonServer interface {
	Walk(context.Context, *WalkRequest) (*WalkReply, error)
	mustEmbedUnimplementedWalkingSkeletonServer()
}

// UnimplementedWalkingSkeletonServer must be embedded to have forward compatible implementations.
type UnimplementedWalkingSkeletonServer struct {
}

func (UnimplementedWalkingSkeletonServer) Walk(context.Context, *WalkRequest) (*WalkReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Walk not implemented")
}
func (UnimplementedWalkingSkeletonServer) mustEmbedUnimplementedWalkingSkeletonServer() {}

// UnsafeWalkingSkeletonServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to WalkingSkeletonServer will
// result in compilation errors.
type UnsafeWalkingSkeletonServer interface {
	mustEmbedUnimplementedWalkingSkeletonServer()
}

func RegisterWalkingSkeletonServer(s grpc.ServiceRegistrar, srv WalkingSkeletonServer) {
	s.RegisterService(&WalkingSkeleton_ServiceDesc, srv)
}

func _WalkingSkeleton_Walk_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WalkRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(WalkingSkeletonServer).Walk(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/skeleton.WalkingSkeleton/Walk",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(WalkingSkeletonServer).Walk(ctx, req.(*WalkRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// WalkingSkeleton_ServiceDesc is the grpc.ServiceDesc for WalkingSkeleton service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var WalkingSkeleton_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "skeleton.WalkingSkeleton",
	HandlerType: (*WalkingSkeletonServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Walk",
			Handler:    _WalkingSkeleton_Walk_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protobuf/skeleton.proto",
}
